ebi-uniprot/uniprot-store

index-config/src/main/solr-config/uniprot-collections/disease/conf/schema.xml, indexer/src/main/java/uk/ac/ebi/uniprot/indexer/common/utils/Constants.java, indexer/src/main/java/uk/ac/ebi/uniprot/indexer/crossref/steps/CrossRefStep.java, indexer/src/main/java/uk/ac/ebi/uniprot/indexer/disease/DiseaseItemReader.java, indexer/src/main/java/uk/ac/ebi/uniprot/indexer/disease/DiseaseLoadJob.java, indexer/src/main/java/uk/ac/ebi/uniprot/indexer/disease/DiseaseLoadStep.java, indexer/src/main/java/uk/ac/ebi/uniprot/indexer/disease/DiseaseProcessor.java, indexer/src/main/java/uk/ac/ebi/uniprot/indexer/proteome/ProteomeEntryConverter.java, indexer/src/main/java/uk/ac/ebi/uniprot/indexer/uniprotkb/processor/UniProtEntryConverter.java, indexer/src/main/resources/application.properties, indexer/src/test/java/uk/ac/ebi/uniprot/indexer/disease/DiseaseLoadJobIT.java, indexer/src/test/java/uk/ac/ebi/uniprot/indexer/disease/DiseaseLoadJobTest.java, indexer/src/test/java/uk/ac/ebi/uniprot/indexer/proteome/ProteomeIndexIT.java, indexer/src/test/java/uk/ac/ebi/uniprot/indexer/test/config/FakeReadDatabaseConfig.java, indexer/src/test/resources/application.properties, indexer/src/test/resources/database/Schema.sql, indexer/src/test/resources/database/TestData.sql, indexer/src/test/resources/uniprotkb/test-humdisease-entries.txt, integration-test/src/test/java/uk/ac/ebi/uniprot/indexer/search/proteome/ProteomeSearchIT.java, uniprot-datastore/src/main/java/uk/ac/ebi/uniprot/datastore/voldemort/uniprot/VoldemortRemoteUniprotEntryStore.java, uniprot-search/src/main/java/uk/ac/ebi/uniprot/search/SolrCollection.java, uniprot-search/src/main/java/uk/ac/ebi/uniprot/search/document/disease/DiseaseDocument.java
Hi @LeonardoGonzales ,
Can you please review the PR?
Thanks,
Shadab
=> TRM-22119 spring batch job with test case for the disease data

uniprot-search/src/main/java/uk/ac/ebi/uniprot/search/field/CrossRefField.java, uniprot-search/src/main/java/uk/ac/ebi/uniprot/search/field/GeneCentricField.java, uniprot-search/src/main/java/uk/ac/ebi/uniprot/search/field/KeywordField.java, uniprot-search/src/main/java/uk/ac/ebi/uniprot/search/field/LiteratureField.java, uniprot-search/src/main/java/uk/ac/ebi/uniprot/search/field/ProteomeField.java, uniprot-search/src/main/java/uk/ac/ebi/uniprot/search/field/ReturnField.java, uniprot-search/src/main/java/uk/ac/ebi/uniprot/search/field/TaxonomyField.java, uniprot-search/src/main/java/uk/ac/ebi/uniprot/search/field/UniParcField.java, uniprot-search/src/main/java/uk/ac/ebi/uniprot/search/field/UniProtField.java
See ticket https://www.ebi.ac.uk/panda/jira/browse/TRM-22624 for details.
=> Use new Json converter refactor

indexer/src/main/java/org/uniprot/store/indexer/common/listener/SolrCommitStepListener.java, indexer/src/main/java/org/uniprot/store/indexer/keyword/KeywordLoadProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/keyword/KeywordLoadStep.java, indexer/src/main/java/org/uniprot/store/indexer/keyword/KeywordStatisticsStep.java, indexer/src/main/java/org/uniprot/store/indexer/literature/processor/LiteratureLoadProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/literature/processor/LiteratureMappingProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/literature/steps/LiteratureLoadStep.java, indexer/src/main/java/org/uniprot/store/indexer/literature/steps/LiteratureMappingStep.java, indexer/src/main/java/org/uniprot/store/indexer/literature/steps/LiteratureStatisticsStep.java, indexer/src/main/java/org/uniprot/store/indexer/taxonomy/processor/TaxonomyProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/taxonomy/steps/TaxonomyDeletedStep.java, indexer/src/main/java/org/uniprot/store/indexer/taxonomy/steps/TaxonomyMergedStep.java, indexer/src/main/java/org/uniprot/store/indexer/taxonomy/steps/TaxonomyNodeStep.java, indexer/src/main/java/org/uniprot/store/indexer/taxonomy/steps/TaxonomyStatisticsStep.java, indexer/src/test/java/org/uniprot/store/indexer/keyword/KeywordJobIT.java, indexer/src/test/java/org/uniprot/store/indexer/literature/LiteratureJobIT.java, indexer/src/test/java/org/uniprot/store/indexer/taxonomy/TaxonomyJobIT.java
for taxonomy, literature and keyword
=> improve solr supporting data solr performance 

index-config/src/main/solr-config/uniprot-collections/uniprot/conf/schema.xml, indexer/src/main/java/org/uniprot/store/indexer/uniprotkb/processor/UniProtEntryConverter.java, indexer/src/test/java/org/uniprot/store/indexer/uniprotkb/processor/UniProtEntryConverterTest.java, uniprot-search/src/main/java/org/uniprot/store/search/document/suggest/SuggestDictionary.java, uniprot-search/src/main/java/org/uniprot/store/search/document/uniprot/UniProtDocument.java
refactoring of suggester index
=> Suggester2

index-config/src/main/solr-config/uniprot-collections/uniprot/conf/schema.xml, indexer/src/main/java/org/uniprot/store/indexer/uniprotkb/processor/UniProtEntryConverter.java, uniprot-search/src/main/java/org/uniprot/store/search/document/uniprot/UniProtDocument.java
Added codes to the following 3 files for Peptide Search Indexing procedure.
index-config/src/main/solr-config/uniprot-collections/uniprot/conf/schema.xml
uniprot-search/src/main/java/org/uniprot/store/search/document/uniprot/UniProtDocument.java
indexer/src/main/java/org/uniprot/store/indexer/uniprotkb/processor/UniProtEntryConverter.java
=> Modified the following files for Peptide Search indexing procedure.

indexer/src/main/java/org/uniprot/store/indexer/crossref/CrossRefJob.java, indexer/src/main/java/org/uniprot/store/indexer/disease/DiseaseLoadJob.java, indexer/src/main/java/org/uniprot/store/indexer/disease/DiseaseProteinCountWriter.java, indexer/src/main/java/org/uniprot/store/indexer/literature/LiteratureSQLConstants.java, indexer/src/main/java/org/uniprot/store/indexer/literature/processor/LiteratureLoadProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/literature/processor/LiteratureMappingProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/literature/processor/LiteratureStatisticsProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/literature/reader/LiteratureMappingItemReader.java, indexer/src/main/java/org/uniprot/store/indexer/literature/reader/LiteratureMappingLineMapper.java, indexer/src/main/java/org/uniprot/store/indexer/literature/steps/LiteratureMappingStep.java, indexer/src/main/java/org/uniprot/store/indexer/subcell/SubcellularLocationJob.java, indexer/src/main/java/org/uniprot/store/indexer/uniprotkb/converter/UniProtEntryCommentsConverter.java, indexer/src/test/java/org/uniprot/store/indexer/literature/LiteratureJobIT.java, indexer/src/test/java/org/uniprot/store/indexer/literature/reader/LiteratureMappingLineMapperTest.java, integration-test/src/main/java/org/uniprot/store/indexer/DataStoreManager.java, pom.xml, uniprot-search/src/main/java/org/uniprot/store/search/SolrQueryUtil.java, uniprot-search/src/main/java/org/uniprot/store/search/field/LiteratureField.java
Index change to couple Literature model change
=> Literature by protein

indexer/src/main/java/org/uniprot/store/indexer/disease/DiseaseProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/literature/processor/LiteratureLoadProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/literature/processor/LiteratureMappingProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/literature/reader/LiteratureMappingItemReader.java, indexer/src/main/java/org/uniprot/store/indexer/proteome/ProteomeEntryConverter.java, indexer/src/main/java/org/uniprot/store/indexer/taxonomy/processor/TaxonomyProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/uniprotkb/config/SuggestionConfig.java, integration-test/src/main/java/org/uniprot/store/indexer/uniprot/mockers/UniProtEntryMocker.java, uniprot-datastore/src/main/java/org/uniprot/store/datastore/uniprotkb/writer/UniProtEntryRetryWriter.java, uniprot-datastore/src/main/java/org/uniprot/store/datastore/voldemort/data/validator/UniprotEntryRetrieveParseVerifier.java, uniprot-search/src/main/java/org/uniprot/store/search/domain/impl/Databases.java
=> REPLEACES INSTANCE CALL SYNTAX TO STATIC SYNTAX

indexer/src/main/java/org/uniprot/store/indexer/proteome/ProteomeEntryConverter.java, integration-test/src/test/java/org/uniprot/store/indexer/search/AbstractValidateAllFieldsExist.java, integration-test/src/test/java/org/uniprot/store/indexer/search/crossref/ValidateAllFieldsExistIT.java, integration-test/src/test/java/org/uniprot/store/indexer/search/keyword/KeywordSearchEngine.java, uniprot-search/src/main/java/org/uniprot/store/search/domain2/JsonLoader.java
formats code due to maven plugin
=> REMOVES NEWINSTANCE TO MAKE BUILDERS CONSISTENT

index-config/src/main/solr-config/uniprot-collections/uniprot/conf/schema.xml, indexer/src/main/java/org/uniprot/store/indexer/uniprotkb/converter/UniProtEntryTaxonomyConverter.java, indexer/src/test/java/org/uniprot/store/indexer/uniprotkb/converter/UniProtKBEntryConverterIT.java, indexer/src/test/java/org/uniprot/store/indexer/uniprotkb/converter/UniProtKBEntryTaxonomyConverterTest.java, integration-test/src/test/java/org/uniprot/store/indexer/search/uniprot/OrganismIT.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/mapper/TaxonomyEntryToUniProtDocument.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/mapper/TaxonomyEntryToUniProtDocumentTest.java, uniprot-config/src/main/resources/search-fields-config/uniprotkb-search-fields.json, uniprot-config/src/test/resources/test-uniprotkb-search-fields.json, uniprot-search/src/main/java/org/uniprot/store/search/document/uniprot/UniProtDocument.java
update facet field from popular organism to model organism (TRM-23607)
=> update facet field from popular organim to model organism (TRM-23607)

uniprot-config/src/main/resources/return-fields-config/uniprotkb-return-fields.json
Add two new return fields namely comment_count and feature_count.
@eddturner - please note that i have cut this branch from Leo's private branch.
=> Trm 23752 add dynamic fields comment feature count

spark-indexer/pom.xml, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/common/util/SolrUtils.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/common/writer/SolrIndexWriter.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/main/IndexHDFSDocumentsInSolrMain.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/suggest/mapper/document/GOToSuggestDocument.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/common/writer/SolrIndexWriterTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/suggest/mapper/document/GOToSuggestDocumentTest.java
Remove solr spark lib and Migrate to spark 3
=> Remove solr spark lib and Migrate to spark 3

uniprot-datastore/src/main/java/org/uniprot/store/datastore/voldemort/VoldemortRemoteJsonBinaryStore.java
Also, getEntries should throw exception immediately upon discovering a requested accession is not in voldemort (this would happen if solr and voldemort are functionally fine, but contain out of sync data (e.g., release 2020_04 and release 2020_05)
=> throw retrievalexception if problem fetching from voldemort.

uniprot-config/src/main/java/org/uniprot/store/config/searchfield/impl/SearchFieldConfigImpl.java, uniprot-config/src/main/resources/search-fields-config/uniprotkb-search-fields.json, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/impl/SearchFieldConfigImplTest.java
add database cross_ref to advanced search (with database category level) and update go_evidences with the correct evidences
=> update AdvancedSearchTerm add cross_ref and go_evidences

uniprot-config/src/main/resources/return-fields-config/uniprotkb-return-fields.json
https://www.ebi.ac.uk/panda/jira/browse/TRM-25066
=> change feature type display name labels to align exactly with what uniprot.org uses

uniprot-config/src/main/resources/search-fields-config/uniprotkb-search-fields.json, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/factory/SearchFieldConfigFactoryTest.java, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/impl/SearchFieldConfigImplTest.java
add uniref_cluster_50, uniref_cluster_90, uniref_cluster_100 and uniparc to uniprotkb-search-fields.json
=> Add Missing search fields

index-config/src/main/solr-config/uniprot-collections/crossref/conf/schema.xml, index-config/src/main/solr-config/uniprot-collections/crossref/conf/solrconfig.xml, index-config/src/main/solr-config/uniprot-collections/disease/conf/schema.xml, index-config/src/main/solr-config/uniprot-collections/disease/conf/solrconfig.xml, index-config/src/main/solr-config/uniprot-collections/keyword/conf/schema.xml, index-config/src/main/solr-config/uniprot-collections/keyword/conf/solrconfig.xml, index-config/src/main/solr-config/uniprot-collections/subcellularlocation/conf/schema.xml, index-config/src/main/solr-config/uniprot-collections/subcellularlocation/conf/solrconfig.xml, index-config/src/main/solr-config/uniprot-collections/suggest/conf/schema.xml, index-config/src/main/solr-config/uniprot-collections/suggest/conf/solrconfig.xml, index-config/src/main/solr-config/uniprot-collections/taxonomy/conf/schema.xml, index-config/src/main/solr-config/uniprot-collections/taxonomy/conf/solrconfig.xml, indexer/src/main/java/org/uniprot/store/indexer/disease/DiseaseProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/keyword/KeywordLoadProcessor.java, indexer/src/main/java/org/uniprot/store/indexer/subcell/SubcellularLocationLoadProcessor.java, indexer/src/test/java/org/uniprot/store/indexer/keyword/KeywordJobIT.java, indexer/src/test/java/org/uniprot/store/indexer/subcell/SubcellularLocationJobIT.java, indexer/src/test/java/org/uniprot/store/indexer/taxonomy/TaxonomyJobIT.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/common/util/SolrUtilsTest.java, uniprot-config/src/main/resources/search-fields-config/crossref-search-fields.json, uniprot-config/src/main/resources/search-fields-config/disease-search-fields.json, uniprot-config/src/main/resources/search-fields-config/keyword-search-fields.json, uniprot-config/src/main/resources/search-fields-config/subcelllocation-search-fields.json, uniprot-config/src/main/resources/search-fields-config/taxonomy-search-fields.json, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/factory/SearchFieldConfigFactoryTest.java, uniprot-search/src/main/java/org/uniprot/store/search/document/disease/DiseaseDocument.java, uniprot-search/src/main/java/org/uniprot/store/search/document/keyword/KeywordDocument.java, uniprot-search/src/main/java/org/uniprot/store/search/document/subcell/SubcellularLocationDocument.java, uniprot-search/src/main/java/org/uniprot/store/search/document/taxonomy/TaxonomyDocument.java
- Remove content field and related changes
=> Support data tuning -  Remove content field and related changes

uniprot-config/src/main/resources/return-fields-config/proteome-return-fields.json
add Proteome genome representation return field for TSV and JSON
=> Proteome genome representation

index-config/src/main/solr-config/uniprot-collections/uniprot/conf/schema.xml, indexer/src/main/java/org/uniprot/store/indexer/uniprotkb/converter/UniProtEntryConverter.java, indexer/src/main/java/org/uniprot/store/indexer/uniprotkb/processor/InactiveEntryConverter.java, indexer/src/test/java/org/uniprot/store/indexer/uniprotkb/converter/UniProtKBEntryConverterIT.java, indexer/src/test/java/org/uniprot/store/indexer/uniprotkb/converter/UniProtKBEntryConverterTest.java, indexer/src/test/java/org/uniprot/store/indexer/uniprotkb/processor/InactiveEntryConverterTest.java, integration-test/src/main/java/org/uniprot/store/indexer/uniprot/mockers/InactiveEntryMocker.java, integration-test/src/test/java/org/uniprot/store/indexer/search/uniprot/AccessionSearchIT.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/converter/InactiveUniprotEntryConverter.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/converter/UniProtEntryConverter.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/converter/InactiveUniprotEntryConverterTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/converter/UniProtKBEntryConverterIT.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/converter/UniProtKBEntryConverterTest.java, uniprot-search/src/main/java/org/uniprot/store/search/SolrQueryUtil.java, uniprot-search/src/main/java/org/uniprot/store/search/document/uniprot/UniProtDocument.java, uniprot-search/src/test/java/org/uniprot/store/search/SolrQueryUtilTest.java
See IT test to understand the use cases. I will be off tomorrow but we can chat on Monday
=> Fix Inactive ids search for uniprot

index-config/src/main/solr-config/uniprot-collections/help/conf/schema.xml, index-config/src/main/solr-config/uniprot-collections/help/conf/solrconfig.xml
Update schema and solrconfig to allow partial matches of words (as requested) and to allow "more like this" queries to be provided by Solr
=> Help fuzzy search

index-config/src/main/solr-config/uniprot-collections/taxonomy/conf/schema.xml, indexer/src/main/java/org/uniprot/store/indexer/taxonomy/processor/TaxonomyProcessor.java, indexer/src/test/java/org/uniprot/store/indexer/taxonomy/TaxonomyJobIT.java, uniprot-config/src/main/resources/search-fields-config/taxonomy-search-fields.json, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/factory/SearchFieldConfigFactoryTest.java, uniprot-search/src/main/java/org/uniprot/store/search/document/taxonomy/TaxonomyDocument.java
- fix taxonomy parent
- fix taxonomy ancestors
- remove root taxonomy from solr index
=> Taxonomy fixes

spark-indexer/src/main/java/org/uniprot/store/spark/indexer/go/evidence/GOEvidencesFileMapper.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/go/evidence/GOEvidencesFileMapperTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/UniProtKBDataStoreIndexerTest.java
See https://www.ebi.ac.uk/panda/jira/browse/TRM-26962 for details.
=> use eco id from file GO.dr_extended

spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/mapper/ChebiToUniProtDocument.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/proteome/mapper/ProteomeTaxonomyStatisticsMapperTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/mapper/ChebiToUniProtDocumentTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/mapper/OrganismJoinMapperTest.java
https://www.ebi.ac.uk/panda/jira/browse/TRM-27118
Add CHEBI inchikey value to cofactor and catalytic activity fields.
=> TRM-27118: add inchikey value to cofactor and catalytic activity fields

pom.xml, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/go/evidence/GOEvidencesFileMapper.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/publication/mapper/MappedReferencesToPublicationDocumentBuilderConverterTest.java, uniprot-config/src/main/resources/return-fields-config/keyword-return-fields.json
see https://www.ebi.ac.uk/panda/jira/browse/TRM-26571 for details
=> remove keyword from return  field

index-config/src/main/solr-config/uniprot-collections/uniprot/conf/schema.xml, indexer/src/test/java/org/uniprot/store/indexer/uniprotkb/processor/InactiveEntryConverterTest.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/converter/InactiveUniprotEntryConverter.java, uniprot-config/src/main/resources/return-fields-config/crossref-return-fields.json, uniprot-config/src/main/resources/return-fields-config/disease-return-fields.json
see https://www.ebi.ac.uk/panda/jira/browse/TRM-26601 for details.
=> make return field stats consistent

spark-indexer/src/main/java/org/uniprot/store/spark/indexer/chebi/ChebiRDDReader.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/chebi/GraphMergeVertexMapper.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiFileMapper.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiPH7RelatedMapper.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiPairMapper.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiRelatedChebiMapper.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiRelatedIdsJoinMapper.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiRelatedIdsMapper.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/suggest/SuggestDocumentsToHDFSWriter.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/suggest/mapper/document/ChebiToSuggestDocument.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/mapper/ChebiToUniProtDocument.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/chebi/ChebiRDDReaderTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/chebi/GraphMergeVertexMapperTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiFileMapperTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiPH7RelatedMapperTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiPairMapperTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiRelatedChebiMapperTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiRelatedIdsJoinMapperTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/chebi/mapper/ChebiRelatedIdsMapperTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/suggest/SuggestDocumentsToHDFSWriterTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/suggest/mapper/document/ChebiToSuggestDocumentTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/mapper/ChebiToUniProtDocumentTest.java, spark-indexer/src/test/resources/2020_02/chebi/chebi.obo, spark-indexer/src/test/resources/2020_02/chebi/chebi_pH7_3_mapping.tsv, spark-indexer/src/test/resources/application.properties
Suggestion
- Add synonyms
- Add Chebi related Ids in the suggest as Well
Chebi Index
- load from rhea chebi.obo file 
- load extra relations from a tsv file
- load extra relationships from chebi file
=> Chebi from rhea db

spark-indexer/src/main/java/org/uniprot/store/spark/indexer/rhea/RheaCompFileMapper.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/rhea/RheaCompRDDReader.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/rhea/model/RheaComp.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/suggest/SuggestDocumentsToHDFSWriter.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/suggest/mapper/document/RheaCompToSuggestDocument.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/suggest/mapper/flatfile/FlatFileToCatalyticActivityRheaComp.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/rhea/RheaCompFileMapperTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/rhea/RheaCompRDDReaderTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/suggest/SuggestDocumentsToHDFSWriterTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/suggest/mapper/document/RheaCompToSuggestDocumentTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/suggest/mapper/flatfile/FlatFileToCatalyticActivityRheaCompTest.java, spark-indexer/src/test/resources/2020_02/rhea/rhea-comp-names.tsv, spark-indexer/src/test/resources/2020_02/uniprotkb/Q9EPI6.sp, spark-indexer/src/test/resources/application.properties
add rhea component name auto complete (suggest)
=> - add rhea comp auto complete (suggest)

uniprot-config/src/main/java/org/uniprot/store/config/searchfield/model/SearchFieldItem.java, uniprot-config/src/main/resources/schema/search-fields-schema.json, uniprot-config/src/main/resources/search-fields-config/uniprotkb-search-fields.json, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/factory/SearchFieldConfigFactoryTest.java, uniprot-config/src/test/resources/test-search-fields-schema.json, uniprot-config/src/test/resources/test-uniprotkb-search-fields.json
I also noticed we were missing Small molecule, UniRef and UniParc from Advanced field list.
=> add tags to advanced search fields

spark-indexer/src/main/java/org/uniprot/store/spark/indexer/suggest/SuggestDocumentsToHDFSWriter.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/suggest/SuggestDocumentsToHDFSWriterTest.java, uniprot-config/src/main/resources/search-fields-config/uniprotkb-search-fields.json, uniprot-search/src/main/java/org/uniprot/store/search/document/suggest/SuggestDictionary.java
Create a suggest for small molecule. It must contains cofactor chebi + catalytic activity chebi data.
=> add small molecule (chebi) suggest

uniprot-search/src/main/java/org/uniprot/store/search/field/validator/FieldRegexConstants.java, uniprot-search/src/test/java/org/uniprot/store/search/field/validator/FieldRegexConstantsTest.java
Allow ID (TRM-27995) and accession with version (TRM-27996) for uniprotkb accession endpoint
=> Allow ID (TRM-27995) and accession with version (TRM-27996)

spark-indexer/src/main/java/org/uniprot/store/spark/indexer/suggest/mapper/document/ECToSuggestDocument.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/suggest/mapper/document/ECToSuggestDocumentTest.java
see for details
https://www.ebi.ac.uk/panda/jira/browse/TRM-26214
=> makes Transferred EC low important

indexer/src/main/java/org/uniprot/store/indexer/uniprotkb/converter/UniProtEntryConverter.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/converter/UniProtEntryConverter.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/converter/UniProtKBEntryConverterTest.java
TRM-28235: enable search and get by id for canonical isoform that does not have isoforms
=> TRM-28235: enable search and get by id for canonical isoform

uniprot-config/src/main/java/org/uniprot/store/config/searchfield/common/AbstractSearchFieldConfig.java, uniprot-config/src/main/java/org/uniprot/store/config/searchfield/common/SearchFieldConfig.java, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/common/AbstractSearchFieldConfigTest.java
=> TRM-28292: Allow search field to be case insensitive in certain case

uniprot-config/src/main/resources/return-fields-config/proteome-return-fields.json
This change is covered in rest IT test
=> TRM-27188: Add strain data into organism_name column

spark-indexer/src/test/java/org/uniprot/store/spark/indexer/suggest/SuggestDocumentsToHDFSWriterTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniparc/UniParcDataStoreIndexerTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniparc/UniParcDocumentsToHDFSWriterTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniparc/UniParcRDDTupleReaderTest.java, spark-indexer/src/test/resources/2020_02/uniparc/UPI000000017F.xml, spark-indexer/src/test/resources/application.properties
I just updated tests to make sure that the current code is able to load multiple UniParc input xml files
=> TRM-28862: UniParc partition files for website to be index

integration-test/src/test/java/org/uniprot/store/indexer/search/uniprot/FTFunctionSearchIT.java, integration-test/src/test/java/org/uniprot/store/indexer/search/uniprot/FTPtmProcessSearchIT.java, integration-test/src/test/java/org/uniprot/store/indexer/search/uniprot/FTSequenceSearchIT.java, uniprot-config/src/main/resources/search-fields-config/uniprotkb-search-fields.json, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/factory/SearchFieldConfigFactoryTest.java, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/impl/SearchFieldConfigImplTest.java
Important: Please do not merge yet, we will need to merge experimental evidence branch first, and due to it, it might fail some tests before it
=> TRM-29078: Remove ftlen fields from advanced search

uniprot-config/src/main/resources/search-fields-config/uniprotkb-search-fields.json, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/factory/SearchFieldConfigFactoryTest.java, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/impl/SearchFieldConfigImplTest.java
Add Any experimental evidence search field in advanced search menu
=> Add Any experimental evidence search field in advanced search menu

spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/converter/UniProtEntryCommentsConverter.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/converter/UniProtKBEntryCommentsConverterTest.java
During the tests, we noticed that any experimental evidence was true for subcellular location when it should not.
=> Fix any experimental evidence for subcellular location

common-job/src/main/java/org/uniprot/store/reader/literature/LiteratureConverter.java, common-job/src/test/java/org/uniprot/store/reader/literature/LiteratureConverterTest.java
Fix error during literature index for 2023_02 release
=> Literature empty rg

spark-indexer/src/main/java/org/uniprot/store/spark/indexer/taxonomy/mapper/TaxonomyLineageRowMapper.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/taxonomy/mapper/TaxonomyLineageRowMapperTest.java
Have a look in the Jira description, if you have any question let me know
=> TRM-29532: Taxonomic lineage reverse

.gitlab-ci.yml, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/common/store/DataStoreIndexer.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/common/store/DataStoreParameter.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniparc/UniParcDataStoreIndexer.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniparc/UniParcDataStoreWriter.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/UniProtKBDataStoreIndexer.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/writer/UniProtKBDataStoreWriter.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniref/UniRefLightDataStoreIndexer.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniref/UniRefMembersDataStoreIndexer.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniref/writer/UniRefLightDataStoreWriter.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniref/writer/UniRefMemberDataStoreWriter.java, spark-indexer/src/main/resources/application.properties, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/main/verifiers/ValidateHPSDocumentsMainTest.java, spark-indexer/src/test/resources/application.properties, uniprot-datastore/pom.xml, uniprot-datastore/src/main/java/org/uniprot/store/datastore/voldemort/VoldemortRemoteJsonBinaryStore.java, uniprot-datastore/src/main/java/org/uniprot/store/datastore/voldemort/light/uniref/VoldemortRemoteUniRefEntryLightStore.java, uniprot-datastore/src/main/java/org/uniprot/store/datastore/voldemort/member/uniref/VoldemortRemoteUniRefMemberStore.java, uniprot-datastore/src/main/java/org/uniprot/store/datastore/voldemort/uniparc/VoldemortRemoteUniParcEntryStore.java, uniprot-datastore/src/main/java/org/uniprot/store/datastore/voldemort/uniprot/VoldemortRemoteUniProtKBEntryStore.java, uniprot-datastore/src/test/java/org/uniprot/store/datastore/voldemort/VoldemortRemoteJsonBinaryStoreTest.java
Please see Jira  [TRM-30169](https://www.ebi.ac.uk/panda/jira/browse/TRM-30169) for details
=> Use brotli compression in Voldemort

spark-indexer/src/test/java/org/uniprot/store/spark/indexer/main/verifiers/ValidateHPSDocumentsMainTest.java, uniprot-config/src/main/java/org/uniprot/store/config/returnfield/config/impl/UniProtKBReturnFieldConfigImpl.java, uniprot-config/src/main/java/org/uniprot/store/config/returnfield/model/ReturnField.java, uniprot-config/src/test/java/org/uniprot/store/config/returnfield/config/AbstractReturnFieldConfigTest.java, uniprot-config/src/test/java/org/uniprot/store/config/returnfield/config/impl/UniProtKBReturnFieldConfigImplTest.java, uniprot-config/src/test/resources/test-return-fields.json
Comments added in the Jira TRM-28411
=> Trm 28411 tsv xref

spark-indexer/src/main/java/org/uniprot/store/spark/indexer/genecentric/GeneCentricCanonicalRDDReader.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/proteome/mapper/ProteomeStatisticsMapper.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/genecentric/GeneCentricCanonicalRDDReaderTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/proteome/mapper/ProteomeStatisticsMapperTest.java
Jira:TRM-30827 (gene count)
Jira:TRM-30801 (Statistics for multiple components/proteomes)
=> Proteome stats fixes

uniprot-config/src/test/java/org/uniprot/store/config/searchfield/impl/SearchFieldConfigImplTest.java
https://www.ebi.ac.uk/panda/jira/browse/TRM-30921
=> re add xref

integration-test/src/main/java/org/uniprot/store/indexer/uniprot/mockers/InactiveEntryMocker.java, spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/mapper/InactiveFileToInactiveEntry.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/InactiveUniProtKBRDDTupleReaderTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/converter/InactiveUniprotEntryConverterTest.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/mapper/InactiveFileToInactiveEntryTest.java
The main change is that we will not return deletedReason when it is Unknown, also description changes
=> TRM-27505: Changes after consortium review

spark-indexer/src/main/resources/default-host-synonyms.txt, spark-indexer/src/main/resources/default-proteome-synonyms.txt, spark-indexer/src/main/resources/default-taxon-synonyms.txt, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/suggest/SuggestDocumentsToHPSWriterTest.java
We already have test case to verify the order. Please see https://github.com/ebi-uniprot/uniprot-rest-api/blob/main/support-data-rest/src/test/java/org/uniprot/api/support/data/suggester/controller/SuggesterControllerIT.java#L150
=> improve suggester as per latest feedback

spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniprot/mapper/ChebiToUniProtDocument.java, spark-indexer/src/test/java/org/uniprot/store/spark/indexer/uniprot/mapper/ChebiToUniProtDocumentTest.java, uniprot-config/src/main/resources/search-fields-config/uniprotkb-search-fields.json
Please see Jira for the details.
=> provide search support by chebi name and synonyms

index-config/src/main/solr-config/uniprot-collections/uniref/conf/schema.xml, integration-test/src/test/java/org/uniprot/store/indexer/search/uniref/UniProtKBIdUPICountSearchIT.java, uniprot-config/src/main/java/org/uniprot/store/config/searchfield/common/AbstractSearchFieldConfig.java, uniprot-config/src/main/resources/search-fields-config/uniref-search-fields.json, uniprot-config/src/test/java/org/uniprot/store/config/searchfield/common/AbstractSearchFieldConfigTest.java, uniprot-config/src/test/resources/test-uniprotkb-search-fields.json, uniprot-search/src/main/java/org/uniprot/store/search/document/uniref/UniRefDocument.java
Please see TRM-32262 for details.
=> rename uniref file uniprot_id to uniprotkb
